version: "3.5"
name: devops-days

services:
  grafana:
    env_file: .env
    container_name: devops-days_grafana
    networks:
      - LAN
    image: grafana/grafana:10.1.2
    ports:
      - 80:3000
    volumes:
      - ./grafana/plugins/magnesium-wordcloud-panel:/var/lib/grafana/plugins/magnesium-wordcloud-panel
      - ./grafana/lib/mongodb-grafana-master/dist:/var/lib/grafana/plugins/mongodb
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards

  grafana-mongodb-proxy:
    container_name: devops-days_grafana-mongodb-proxy
    networks:
      - LAN
    image: node:18
    volumes:
      - ./grafana/lib/mongodb-grafana-master:/mongodb_grafana
    ports:
      - 3333:3333
    command:
      - /bin/bash
      - -c
      - |
        cd mongodb_grafana
        npm i && npm run server

networks:
  LAN:
    driver: bridge
    name: devops-days
