version: "3.5"
name: devops-days

services:
  grafana:
    container_name: devops-days_grafana
    networks:
      - LAN
    image: grafana/grafana:latest
    ports:
      - 80:3000
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/lib/mongodb-grafana-master/dist:/var/lib/grafana/plugins/mongodb
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/storage:/var/lib/grafana

  grafana-mongodb-proxy:
    container_name: devops-days_grafana-mongodb-proxy
    networks:
      - LAN
    image: node:18
    volumes:
      - ./grafana/lib/mongodb-grafana-master:/mongodb_grafana
    ports:
      - 3333:3333
    command:
      - /bin/bash
      - -c
      - |
        cd mongodb_grafana
        npm run server

networks:
  LAN:
    driver: bridge
    name: devops-days
