{
 "title": "DevOps Days Taipei 2023 part1",
 "description": "TrendMicro dashboard for DevOps Days Taipei 2023 1~4",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "你的工作性質屬於",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires.aggregate([\n{\"$match\": {\"answer-0\": {\"$nin\": [\"\"]}}},\n{\"$group\":{ \"_id\": \"$answer-0\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "DevOps 的經驗",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires.aggregate([\n{\"$match\": {\"answer-1\": {\"$in\": [\"未滿一年\",\"1~3年\",\"3~4年\",\"5年以上\"]}}},\n{\"$group\":{ \"_id\": \"$answer-1\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "您使用的程式語言",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-2.aggregate([\n{\"$group\":{ \"_id\": \"$answer-2\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "是否有接觸過網絡協議的相關經驗",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.questionnaires.aggregate([\n{\"$match\": {\"answer-3\": {\"$in\": [\"剛入門\",\"熟門熟路\",\"已上手\",\"這個世界好難懂\"]}}},\n{\"$group\":{ \"_id\": \"$answer-3\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  }
 ]
}