{
 "title": "DevOps Days Taipei 2023 part2",
 "description": "TrendMicro dashboard for DevOps Days Taipei 2023 5~8",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "目前使用的版本控制服務",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "db.questionnaires_answer-4.aggregate([\n{\"$group\":{ \"_id\": \"$answer-4\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "目前使用的專案管理工具",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires_answer-5.aggregate([\n{\"$group\":{ \"_id\": \"$answer-5\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "自動化測試項目",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-6.aggregate([\n{\"$group\":{ \"_id\": \"$answer-6\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "使用的雲端服務",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-7.aggregate([\n{\"$group\":{ \"_id\": \"$answer-7\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  }
 ]
}