{
 "title": "DevOps Days Taipei 2023 part3",
 "description": "TrendMicro dashboard for DevOps Days Taipei 2023 9~12",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "使用中的基礎設施的架構",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "target": "db.questionnaires_answer-8.aggregate([\n{\"$group\":{ \"_id\": \"$answer-8\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "基礎設施部署工具",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires_answer-9.aggregate([\n{\"$group\":{ \"_id\": \"$answer-9\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "是否使用過 Secret management 管理密碼",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.questionnaires.aggregate([\n{\"$match\": {\"answer-10\": {\"$in\": [\"Yes\", \"No\"]}}},\n{\"$group\":{ \"_id\": \"$answer-10\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "使用的配置管理工具",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-11.aggregate([\n{\"$group\":{ \"_id\": \"$answer-11\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  }
 ]
}