{
 "title": "DevOps Days Taipei 2023 part4",
 "description": "TrendMicro dashboard for DevOps Days Taipei 2023 9~12",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "使用的 CI/CD 工具",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires_answer-12.aggregate([\n{\"$group\":{ \"_id\": \"$answer-12\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "使用的容器化管理工具",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.questionnaires_answer-13.aggregate([\n{\"$group\":{ \"_id\": \"$answer-13\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "使用過的系統監控軟體",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-14.aggregate([\n{\"$group\":{ \"_id\": \"$answer-14\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  },
  {
   "title": "使用過的 Logs 管理工具",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "db.questionnaires_answer-15.aggregate([\n{\"$group\":{ \"_id\": \"$answer-15\", \"count\": { \"$sum\": 1}}}\n]);",
     "type": "table"
    }
   ]
  }
 ]
}