name: github-actions
on:
  push:
    branches:
      - main
  repository_dispatch:
    type:
      - submit-request

jobs:
  Send_To_MongoDB:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Questionnaires data
        env:
          QUESTIONNAIRES_DATA: ${{ github.event.client_payload.questionnaires }}
        run: echo $QUESTIONNAIRES_DATA > questionnaires.json

      - name: Install MongoDB tools
        env:
          EBE_FILE_NAME: mongodb-database-tools-ubuntu2004-x86_64-100.8.0.deb
        run: |
          sudo apt-get update && sudo apt-get -y install curl
          curl -O https://fastdl.mongodb.org/tools/db/${{ env.EBE_FILE_NAME }} && sudo apt install ./${{ env.EBE_FILE_NAME }}

      - name: Insert questionnaires to MongoDB
        if: github.event.client_payload.questionnaires != ''
        run: |
          mongoimport '${{ secrets.MONGODB_ATLAS_CONN_STR }}' --db=2023-tw-devops-day --collection=questionnaires --mode=insert --type=json --file=questionnaires.json

  Build_And_Deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF_NAME }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        working-directory: ./questionnaires
        run: npm install

      - name: Build
        working-directory: ./questionnaires
        run: npm run build

      - name: Move questionnaires.yml file to build directory
        run: mv questionnaires.yml ./questionnaires/build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./questionnaires/build
          git-config-name: "GitHub Actions Deploy"
          commit-message: "release: v1.0.${{ github.run_number }}"
